;;; datagrid-verbs.el --- Transformation verbs for datagrid -*- lexical-binding: t; -*-

;; Copyright (C) 2025 Joshua Lambert
;; Author: Joshua Lambert <jlambert@missouristate.edu>
;; Maintainer: Joshua Lambert <jlambert@missouristate.edu>
;; Keywords: tools, convenience
;; AI: This file contains code generated by LLMs.

;; This file is NOT part of GNU Emacs.

;; GNU Emacs is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;;; Commentary:

;; Datagrid transformation verbs that take a datagrid and return a
;; datagrid: head, mutate, rename, add-column, add-row, add-data,
;; set-headings, select, slice, remove-column, remove-row, sort,
;; rows-patch, coalesce, plus the mask-based filter helpers
;; (create-mask, filter-by-mask).

;; Verbs that are tightly coupled to reductions (summarize, group-by,
;; distinct) live in datagrid-stats.el instead.

;;; Code:
(require 'cl-lib)
(require 'seq)
(require 'datagrid)

(defun datagrid-head (datagrid &optional column-num row-num)
  "Return the first ROW-NUM rows and COLUMN-NUM columns of DATAGRID.
COLUMN-NUM is the number of columns (default 5). ROW-NUM is the number
of rows (default 5)."
  (let* ((col-num (min (or column-num 5) (length datagrid)))
	 (row-num (or row-num 5)))
    (vconcat
     (cl-loop for x from 0 below col-num
	      for new = (datagrid-column-copy (elt datagrid x))
	      do (setf (datagrid-column-data new)
		       (seq-take (datagrid-pull datagrid x) row-num))
	      collect new))))

(defun datagrid-mutate (datagrid new-heading fn &rest source-cols)
  "Add or replace a column produced by applying FN row-wise.
DATAGRID is a datagrid. NEW-HEADING is the heading for the produced
column; if a column with that heading already exists it is replaced,
otherwise a new column is appended. FN receives one value per
SOURCE-COL, in order. SOURCE-COLS are zero-based integer indices."
  (let* ((n-rows (length (datagrid-column-data (aref datagrid 0))))
	 (col-vecs (mapcar (lambda (i) (datagrid-column-data (aref datagrid i)))
			   source-cols))
	 (new-data (make-vector n-rows nil)))
    (dotimes (r n-rows)
      (aset new-data r
	    (apply fn (mapcar (lambda (v) (aref v r)) col-vecs))))
    (let* ((new-col (datagrid-column-make :heading new-heading :data new-data))
	   (existing (cl-position new-heading
				  (datagrid-get-headings datagrid)
				  :test #'equal))
	   (copied (vconcat (mapcar #'datagrid-column-copy datagrid))))
      (if existing
	  (progn (setf (aref copied existing) new-col)
		 copied)
	(vconcat copied (vector new-col))))))

(defun datagrid-rename (datagrid col-or-renames &optional new-heading)
  "Return a new DATAGRID with one or more headings renamed.
If NEW-HEADING is non-nil, COL-OR-RENAMES is a single column index or
heading and that column's heading becomes NEW-HEADING. Otherwise
COL-OR-RENAMES is an alist ((OLD-OR-IDX . NEW) ...)."
  (let ((new-dg (vconcat (mapcar #'datagrid-column-copy datagrid))))
    (if new-heading
	(let ((idx (datagrid--resolve-col datagrid col-or-renames)))
	  (setf (datagrid-column-heading (aref new-dg idx)) new-heading))
      (dolist (pair col-or-renames)
	(let ((idx (datagrid--resolve-col datagrid (car pair))))
	  (setf (datagrid-column-heading (aref new-dg idx)) (cdr pair)))))
    new-dg))

(defun datagrid-add-column (datagrid &rest datagrid-columns)
  "Add one or more datagrid-column structs to a datagrid.
DATAGRID is a datagrid. DATAGRID-COLUMNS is a list of datagrid-column
structs. The new columns are always expanded or truncated to fit the
length of the existing columns. All datagrid columns must have the same
length."
  (interactive)
  (when-let*
      ((datagridp (datagridp datagrid))
       (datagrid-cols-p (not (member nil (mapcar #'datagrid-column-p
						 datagrid-columns))))
       ;; Get the length of the data in datagrid columns. This
       ;; is the length the new sequences must conform to.
       (col-len (length (datagrid-column-data (aref datagrid 0))))
       ;; Truncate or expand the new data sequence slots.
       (truncd (mapcar (lambda (dg-c) (datagrid-column-set-length dg-c col-len))
		       datagrid-columns)))
    (seq-concatenate 'vector datagrid truncd)))

(defun datagrid-add-row (datagrid seq)
  "Add elements to the end of each datagrid-column.
DATAGRID a datagrid structure. SEQ is a list of sequences. Each of the
sequences in SEQ must be of equal length to the number of
datagrid-columns in datagrid."
  (interactive)
  (unless (datagridp datagrid)
    (error "DATAGRID is not a datagrid structure"))
  (unless (apply #'= (mapcar #'length seq))
    (error "The sequences in SEQ are not of equal length"))
  (unless (= (length datagrid) (length (car seq)))
    (error (concat "The number of datagrid columns is not "
		   "equal to the length of sequences in SEQ.")))
  (let ((trans-seq (apply #'cl-mapcar #'list seq)))
    (vconcat (cl-loop for struct across datagrid
		      collect (datagrid--column-add-data struct (pop trans-seq))))))

(defun datagrid--add-data-by-column (datagrid seqs)
  "Add data to DATAGRID columns.
SEQS is a sequence of sequences. Each sub-sequence is one column's data.
The sequences of data to add must be in the same order as the
datagrid-columns in DATAGRID. The length of SEQS must be equal to the
length of datagrid. If the sequences added are not of equal length, then
nil will be padded onto other columns to make the data equal."
  (let ((max-len (seq-max (seq-map #'length seqs))))
    (vconcat
     (cl-loop for x from 0 below (length seqs)
	      for new-seq = (seq-concatenate
			     'vector (elt seqs x)
			     (make-list (- max-len (length (elt seqs x))) nil))
	      collect (datagrid--column-add-data (elt datagrid x)
						 new-seq)))))

(defun datagrid-add-data (datagrid seqs &optional horizontal)
  "Add elements to each datagrid-column.
DATAGRID a datagrid structure. SEQS is a sequence of sequences. If
HORIZONTAL is nil, then each sub-sequence is one column's data. If non-nil,
then each sequence is one row's data. The default is nil. The sequences
are extended to keep datagrid-column-data lengths equal.

The sequences of data to add must be in the same order as the
datagrid-columns in DATAGRID."
  (interactive)
  (unless (datagridp datagrid)
    (error "DATAGRID is not a datagrid structure"))
  (if horizontal
      (datagrid--add-data-by-column datagrid (datagrid-safe-transpose seqs))
    (datagrid--add-data-by-column datagrid seqs)))

(defun datagrid-set-headings (datagrid heading-list)
  "Set all DATAGRID headings using HEADING-LIST.
HEADING-LIST is a list of strings where each string is a heading name.
The headings in the list must be in the same order as the
datagrid-columns in the datagrid."
  (cl-loop for x from 0 below (length datagrid)
	   do (setf (datagrid-column-heading (elt datagrid x))
		    (nth x heading-list)))
  datagrid)

(defun datagrid-select (datagrid &rest cols)
  "Return a new datagrid containing only COLS, in the order given.
Each element of COLS is a zero-based integer index or a heading string."
  (vconcat (mapcar (lambda (c)
		     (datagrid-column-copy
		      (aref datagrid (datagrid--resolve-col datagrid c))))
		   cols)))

(defun datagrid-slice (datagrid &rest row-indices)
  "Return a new datagrid containing only the rows at ROW-INDICES.
ROW-INDICES are zero-based row numbers."
  (datagrid--slice-rows datagrid row-indices))

(defun datagrid-remove-column (datagrid &rest cols)
  "Return DATAGRID without the columns in COLS.
Each element of COLS is a zero-based integer index or a heading string."
  (when (datagridp datagrid)
    (let* ((drop (mapcar (lambda (c) (datagrid--resolve-col datagrid c)) cols))
	   (keep (cl-loop for i from 0 below (length datagrid)
			  unless (memq i drop) collect i)))
      (apply #'datagrid-select datagrid keep))))

(defun datagrid-remove-row (datagrid index)
  "Remove the DATAGRID row at INDEX.
This function provides a new datagrid with the INDEX row eliminated."
  (interactive)
  (vconcat
   (cl-loop for elt across datagrid
	    collect (let ((new-col-data (datagrid-column-copy
					 datagrid)))
		      (setf (datagrid-column-data new-col-data)
			    (vconcat (seq-take (datagrid-column-data elt)
					       index)
				     (seq-drop (datagrid-column-data elt)
					       (1+ index))))
		      new-col-data))))

(defun datagrid-sort (datagrid index)
  "Sort a datagrid by a specific column.
DATAGRID is a vector of vectors. INDEX is the zero based index of the
column to sort by, or a heading string. This function assumes that
elements in one column are of like data type and will cause errors if
they are not. Created with the help of Claude.ai."
  ;; TODO: Recreate this with an indirect sorting method as suggested at
  ;; https://www.reddit.com/r/emacs/comments/1lv24a7/comment/n22kkbp/?context=3
  (let* ((index (datagrid--resolve-col datagrid index))
	 (new-dg (vconcat (cl-loop for col across datagrid
				   collect (datagrid-column-copy col))))
	 (sort-col-data (datagrid-column-data (aref new-dg index)))
	 (sort-col-length (length sort-col-data))
	 (indexed-vals (cl-loop for i from 0 below sort-col-length
				collect (cons i (aref sort-col-data i))))
	 (sorted-pairs
	  (seq-sort-by #'cdr #'datagrid-unknown-type-sort indexed-vals))
	 (new-indices (vconcat (mapcar #'car sorted-pairs))))
    (dotimes (col-idx (length new-dg))
      (let* ((col-data (datagrid-column-data (aref new-dg col-idx)))
             (new-col-data (make-vector sort-col-length nil)))
	(dotimes (i sort-col-length)
          (setf (aref new-col-data i) (aref col-data (aref new-indices i))))
	(setf (datagrid-column-data (aref new-dg col-idx)) new-col-data)))
    new-dg))

(cl-defun datagrid-rows-patch (dg1 dg2 &key on cols)
  "Return a copy of DG1 with empty cells filled from matching rows of DG2.
This is the dplyr `rows_patch' operation: a keyed cross-table fill
that never overwrites existing non-empty values.

ON identifies the join key. It accepts an integer (same column
index in both grids), a string (heading present in both), or a
cons (X . Y) for per-grid index or heading. Keys are compared
with `equal'; empty keys (nil or empty string) never match. When
DG2 has duplicate keys, the first occurrence wins.

COLS is an alist ((FILL . SOURCE) ...). FILL is a column ref in
DG1 to fill and SOURCE is a column ref in DG2 to draw values
from. Each ref is an integer index or a heading string.

For each pair, every row of DG1 whose FILL value is nil or the
empty string is looked up by its key in DG2. When a match is
found and DG2's SOURCE value for that row is non-empty, the
value is copied into the returned datagrid. Existing non-empty
FILL values are left as is; DG1 is not modified.

Keys are compared `equal'-strictly: \"123\" and 123 are not
equal. Normalize types before calling if your key columns came
from different sources."
  (unless on (error ":on is required"))
  (unless cols (error ":cols is required"))
  (cl-labels ((empty-p (v) (or (null v) (and (stringp v) (string-empty-p v))))
	      (build-lookup (keys vals)
		(let ((ht (make-hash-table :test #'equal)))
		  (cl-loop for k across keys
			   for v across vals
			   unless (or (empty-p k) (empty-p v) (gethash k ht))
			   do (puthash k v ht))
		  ht)))
    (let* ((on-pair (pcase on
		      ((or (pred integerp) (pred stringp))
		       (cons (datagrid--resolve-col dg1 on)
			     (datagrid--resolve-col dg2 on)))
		      (`(,a . ,b)
		       (cons (datagrid--resolve-col dg1 a)
			     (datagrid--resolve-col dg2 b)))
		      (_ (error "Bad :on value: %S" on))))
	   (on1 (car on-pair))
	   (on2 (cdr on-pair))
	   (keys1 (datagrid-column-data (aref dg1 on1)))
	   (keys2 (datagrid-column-data (aref dg2 on2)))
	   (result (copy-sequence dg1)))
      (dolist (pair cols result)
	(let* ((fill-idx (datagrid--resolve-col dg1 (car pair)))
	       (source-idx (datagrid--resolve-col dg2 (cdr pair)))
	       (lookup (build-lookup
			keys2
			(datagrid-column-data (aref dg2 source-idx))))
	       (new-col (datagrid-column-copy (aref dg1 fill-idx)))
	       (new-data (copy-sequence (datagrid-column-data new-col))))
	  (cl-loop for i from 0 below (length new-data)
		   when (empty-p (aref new-data i))
		   do (when-let ((found (gethash (aref keys1 i) lookup)))
			(setf (aref new-data i) found)))
	  (setf (datagrid-column-data new-col) new-data)
	  (setf (aref result fill-idx) new-col))))))

(defun datagrid-coalesce (datagrid &rest col-groups)
  "Row-wise coalesce one or more groups of columns in DATAGRID.
Each group in COL-GROUPS is a list of column refs (integer index or
heading string). For each group, the first column's data is replaced
row-wise by the first non-empty value found across the group, where
\"empty\" means nil or the empty string. The non-first columns of
each group are dropped from the result. Other columns are unchanged.

Useful after `datagrid-full-join' to merge `email'/`email_2' style
sibling columns into one."
  (cl-labels ((empty-p (v) (or (null v) (and (stringp v) (string-empty-p v)))))
    (let* ((groups (mapcar (lambda (g)
			     (mapcar (lambda (c) (datagrid--resolve-col datagrid c))
				     g))
			   col-groups))
	   (n-rows (length (datagrid-column-data (aref datagrid 0))))
	   (drops (apply #'append (mapcar #'cdr groups)))
	   (new-dg (vconcat (mapcar #'datagrid-column-copy datagrid))))
      (dolist (group groups)
	(let* ((target (car group))
	       (vecs (mapcar (lambda (i) (datagrid-column-data (aref datagrid i)))
			     group))
	       (out (make-vector n-rows nil)))
	  (dotimes (r n-rows)
	    (aset out r (seq-some (lambda (v) (let ((x (aref v r)))
						(unless (empty-p x) x)))
				  vecs)))
	  (setf (datagrid-column-data (aref new-dg target)) out)))
      (vconcat (cl-loop for col across new-dg
			for i from 0
			unless (memq i drops)
			collect col)))))

(defun datagrid-create-mask (datagrid pred index)
  "Create a mask for a DATAGRID column at INDEX.
PRED is a function of one argument. It will operate on the
datagrid column at INDEX. INDEX is zero based, or a string naming
the column heading (resolved via `datagrid-col-index-by-header').

This simply returns a vector.

See the Info Manual for built-in predicates, equality functions,
and other useful functions to make predicate functions:

2.7 Type Predicates
2.8 Equality Predicates
3.3 Type Predicates for Numbers
3.4 Comparison of Numbers
4.2 Predicates for Strings
4.5 Comparison of Characters and Strings
5.2 Predicates on Lists
32.2 Predicates on Markers

Other common predicate function examples using lambdas:

 (lambda (x) (= x 15))
 (lambda (x) (eq x 15))
 (lambda (x) (equal x 15))
 (lambda (x) (string-equal x \"2025-03-31\"))
 (lambda (x) (string-prefix-p x \"2025\"))
 (lambda (x) (string-prefix-p x \"2025\"))
 (lambda (x) (> x \"2025\"))
 (lambda (x) (<= x \"2025\"))"
  (interactive)
  (let* ((idx (datagrid--resolve-col datagrid index))
	 (struct (elt datagrid idx))
	 (vec (datagrid-column-data struct))
	 (mask (and (vectorp datagrid)
		    (> (length datagrid) 0)
		    (vectorp vec)
		    (cl-map 'vector pred vec))))
    mask))

(defun datagrid-filter-vector-by-mask (column-struct mask)
  "Filter a datagrid-column struct by a boolean MASK.
COLUMN-STRUCT is a datagrid-column structure. MASK must be a vector
with the same length as datagrid columns and the values must only be t
or nil. It is typically created by datagrid-create-mask-s. This is a
helper function for DATAGRID-FILTER-BY-MASK. It returns a
datagrid-column structure that copies the original but with the data
slot filtered."
  (let ((vec (datagrid-column-data column-struct))
	(new (datagrid-column-copy column-struct)))
    (setf (datagrid-column-data new)
	  (vconcat (cl-loop for m across mask
			    for v across vec
			    when m collect v)))
    new))

(defun datagrid-filter-by-mask (datagrid mask)
  "Use a boolean MASK to filter a DATAGRID.
MASK must be a sequence with the same length as datagrid columns
and the values must only be t or nil. The function returns a
DATAGRID. You can use DATAGRID-CREATE-MASK to create a mask.

The following code show an example workflow when using masks.

 (let* ((mygrid (datagrid-from-csv-buffer \"name-of-file.csv\" t))
        (index (datagrid-col-index-by-header mygrid \"heading-name\"))
        (func (lambda (x) (string-equal x \"filter-string\")))
        (mask (datagrid-create-mask mygrid func index)))
   (datagrid-filter-by-mask mygrid mask))"
  (let ((mask-vec (vconcat mask)))
    (vconcat
     (cl-loop for vec across datagrid
	      collect (datagrid-filter-vector-by-mask vec mask-vec)))))

(provide 'datagrid-verbs)
;;; datagrid-verbs.el ends here
