;;; datagrid-stats.el --- Reductions, statistics, and reports for datagrid -*- lexical-binding: t; -*-

;; Copyright (C) 2025 Joshua Lambert
;; Author: Joshua Lambert <jlambert@missouristate.edu>
;; Maintainer: Joshua Lambert <jlambert@missouristate.edu>
;; Keywords: tools, convenience
;; AI: This file contains code generated by LLMs.

;; This file is NOT part of GNU Emacs.

;; GNU Emacs is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;;; Commentary:

;; Reductions, descriptive statistics, and summary reports for
;; datagrid. Also hosts the dplyr verbs that are tightly coupled to
;; reduction machinery: distinct, group-by, and summarise.

;;; Code:
(require 'cl-lib)
(require 'seq)
(require 'calc)
(require 'calc-vec)
(require 'datagrid)

(defun datagrid-distinct (datagrid &rest cols)
  "Return DATAGRID with duplicate rows removed.
With no COLS, rows are deduped considering all columns. With one or
more COLS (integer indices or heading strings), rows are deduped
considering only those columns, and only those columns appear in the
result.

Note: row-level dedup walks all rows and hashes the cross-column key
for each one, so it can be slow on large datagrids."
  (let* ((indices (if cols
		      (mapcar (lambda (c) (datagrid--resolve-col datagrid c))
			      cols)
		    (number-sequence 0 (1- (length datagrid)))))
	 (n-rows (length (datagrid-column-data (aref datagrid 0))))
	 (col-vecs (mapcar (lambda (i) (datagrid-column-data (aref datagrid i)))
			   indices))
	 (seen (make-hash-table :test 'equal))
	 (kept nil))
    (dotimes (r n-rows)
      (let ((key (mapcar (lambda (v) (aref v r)) col-vecs)))
	(unless (gethash key seen)
	  (puthash key t seen)
	  (push r kept))))
    (let ((subset (vconcat (mapcar (lambda (i)
				     (datagrid-column-copy (aref datagrid i)))
				   indices))))
      (datagrid--slice-rows subset (nreverse kept)))))

(defun datagrid-group-by (datagrid index)
  "Group data in DATAGRID according to INDEX.
INDEX is a zero-based column number or a heading string. The resulting
structure is a 3D vector. The first dimension is a vector of groups
which were formed by grouping rows of the datagrid by unique values in
COL-VALUES. The 2nd dimension vector contains the original datagrid
vectors filtered for only that group. The 3rd dimension vector contains
the data from one column for one group."
  (let* ((index (datagrid--resolve-col datagrid index))
	 (col-data (datagrid-column-data (aref datagrid index)))
	 (index-map (make-hash-table :test #'equal))
	 (n (length col-data)))
    (cl-loop for i from 0 below n
	     do (push i (gethash (aref col-data i) index-map)))
    (vconcat
     (cl-loop for val being the hash-keys of index-map
	      using (hash-values idxs)
	      collect (list val
			    (datagrid--select-rows
			     datagrid (nreverse idxs)))))))

(defun datagrid-reduce-vec (datagrid function index &optional code convert)
  "Reduce a FUNCTION across DATAGRID data at INDEX.
Return the result of calling FUNCTION on the data vector at INDEX
from a datagrid column. If CODE is nil, then column data is not
decoded. If CODE is non-nil then decode data using the alist in
the code slot of the datagrid column structure. If CONVERT is t,
loop over the data to convert strings to numbers as needed.

Examples:
\ (datagrid-reduce-vec datagrid-example #`+ 2)
\ (datagrid-reduce-vec datagrid #`max index code convert)
\ (datagrid-reduce-vec datagrid #`+ index code convert)

This function and documentation string are derived from
SEQ-REDUCE."
  (interactive)
  (unless (datagridp datagrid)
    (error "Argument must be a datagrid"))
  (let* ((index (datagrid--resolve-col datagrid index))
	 (vec (if code
		  (datagrid-column-decode datagrid index)
		(datagrid-column-data (aref datagrid index))))
	 (vec (if convert
		  (datagrid-unknown-type-to-number vec)
		vec)))
    (seq-reduce function vec 0)))

(defun datagrid-prep-for-calc (item)
  "Prepare the ITEM for use in a Calc function.
ITEM should be a string or number. The following steps will be taken in
order: all data values will be converted to a number or return an error;
floating point numbers will be converted to a format Calc functions can
understand. Calc floating points must look like (float 25 -2).

Use this to prepare a sequence of items.

Example: (seq-keep #\\='datagrid-prep-for-calc your-seq)"
  (let* ((it (cond ((stringp item) (if (equal item "")
				       nil
				     (string-to-number item)))
		   ((numberp item) item)
		   ((null item) item)
		   (t (error "%s cannot be coerced into a number"
			     item)))))
    (if (floatp it)
	(math-read-number (number-to-string it))
      it)))

(defun datagrid-calc-function-wrapper (func-abbrev lst)
  "Call a Calc vector function for a list.
FUNC-ABBREV is a string which comes from a Calc function.
LST is a list. This function only handles single-variable vector
statistics.

Examples:
\ (datagrid-calc-function-wrapper \"vmax\" `(1 2 3 4 5 5000))
\ (datagrid-calc-function-wrapper \"vflat\" `(1 2 3 4 5 5000))
\ (datagrid-calc-function-wrapper \"vmedian\" `(1 2 3 4 5 5000))

Lists must include only numbers, those numbers must be in Calc
understandable form, and not include nil. Calc cannot handle
decimal numbers for division. Use the following to prepare a
list.

  (seq-keep #`datagrid-prep-for-calc your-list)

You can find Calc functions by doing \\[describe-function] (C-h
f) and typing calcFunc- and viewing completions. You can also
find the functions in the Calc documentation in many places. Find
the single-variable statistics at 10.7.1 - Single Variable
Statistics. That list includes:

vcount, vsum, vprod, vmax, vmean, vmeane, vmedian, vhmean,
vgmean, agmean, rms, vsdev, vpsdev, vvar, vpvar, vflat

Also see the Calc function index. Usually you will find the Emacs
Lisp function name followed by the abbreviation. For
example (calc-vector-mean) [vmean]."
  (let* ((func-name (intern (concat "calcFunc-" func-abbrev)))
	 (result (funcall func-name (cons 'vec lst))))
    (string-to-number (math-format-number (math-float result)))))

(defun datagrid-reduce-vec-calc (datagrid func-abbrev index &optional code convert)
  "Reduce an Emacs Calc function, FUNC-ABBREV, across DATAGRID data.
Return the result of calling the Calc function FUNC-ABBREV on the
data in a datagrid column at INDEX. If CODE is nil, then column
data is not decoded. If CODE is non-nil then decode data using
the alist in the code slot of the datagrid column structure. If
CONVERT is t, loop over the data to convert strings to numbers as
needed.

FUNC-ABBREV is a string for the Calc abbreviation for a function.
You can find these functions by doing \\[describe-function] (C-h f) and typing calcFunc-
and viewing completions. You can also find the functions in the
Calc documentation in many places. Find the single-variable
statistics at 10.7.1 - Single Variable Statistics. That list
includes:

vcount, vsum, vprod, vmax, vmean, vmeane, vmedian, vhmean,
vgmean, agmean, rms, vsdev, vpsdev, vvar, vpvar, vflat

Also see the Calc function index. Usually you will find the Emacs
Lisp function name followed by the abbreviation. For
example (calc-vector-mean) [vmean].

Nil data values are discarded before the calculation."
  (interactive)
  (unless (datagridp datagrid)
    (error "Argument must be a datagrid"))
  (let* ((index (datagrid--resolve-col datagrid index))
	 (vec (if code
		  (datagrid-column-decode datagrid index)
		(datagrid-column-data (aref datagrid index))))
	 (vec (if convert
		  (datagrid-unknown-type-to-number vec)
		vec))
	 (vec (delq nil (append vec nil))))
    (when vec (datagrid-calc-function-wrapper func-abbrev vec))))

(defun datagrid-summarise (datagrid &rest specs)
  "Compute reductions over DATAGRID columns and return an alist.
Each spec in SPECS is a plist with the following keywords:
  :name    heading for this reduction (used as the alist key)
  :fn      reducer (binary function for `seq-reduce', or a Calc
           abbreviation string when :calc is non-nil)
  :col     column index or heading string
  :code    non-nil to decode the column data first
  :convert non-nil to convert strings to numbers first
  :calc    non-nil to interpret :fn as a Calc function abbreviation

Returns ((NAME . VALUE) ...) in the order of SPECS."
  (mapcar (lambda (spec)
	    (let* ((name (plist-get spec :name))
		   (fn (plist-get spec :fn))
		   (col (plist-get spec :col))
		   (code (plist-get spec :code))
		   (convert (plist-get spec :convert))
		   (calc (plist-get spec :calc))
		   (idx (datagrid--resolve-col datagrid col)))
	      (cons name
		    (if calc
			(datagrid-reduce-vec-calc datagrid fn idx code convert)
		      (datagrid-reduce-vec datagrid fn idx code convert)))))
	  specs))

(cl-defun datagrid-count (datagrid col &key sort name code)
  "Count occurrences of values in column COL of DATAGRID.
COL is a zero-based integer index or heading string. Returns a
two-column datagrid: the unique values from COL, plus a count column.
If SORT is non-nil, rows are ordered by descending count. NAME is the
heading of the count column (default \"n\"). If CODE is non-nil, decode
the source column's data before counting."
  (unless (datagridp datagrid)
    (error "Argument must be a datagrid"))
  (let* ((idx (datagrid--resolve-col datagrid col))
	 (heading (datagrid-column-heading (aref datagrid idx)))
	 (count-name (or name "n"))
	 (pairs (datagrid--frequencies-alist datagrid idx code)))
    (unless sort
      (setq pairs (seq-sort-by #'car #'datagrid-unknown-type-sort pairs)))
    (vector (datagrid-column-make :heading heading
				  :data (vconcat (mapcar #'car pairs)))
	    (datagrid-column-make :heading count-name
				  :data (vconcat (mapcar #'cdr pairs))))))

(defun datagrid--frequencies-alist (datagrid index code)
  "Return ((value . count) ...) for column INDEX of DATAGRID.
Sorted by count descending. If CODE is non-nil, decode first."
  (unless (datagridp datagrid)
    (error "Argument must be a datagrid"))
  (let* ((index (datagrid--resolve-col datagrid index))
	 (vec (if code
		  (datagrid-column-decode datagrid index)
		(datagrid-column-data (aref datagrid index))))
	 (counts (make-hash-table :test 'equal))
	 result)
    (cl-loop for item across vec
	     do (puthash item (1+ (gethash item counts 0)) counts))
    (maphash (lambda (k v) (push (cons k v) result)) counts)
    (nreverse (seq-sort-by #'cdr #'datagrid-unknown-type-sort result))))

(defun datagrid-column-frequencies (datagrid index &optional code)
  "Find the frequency of elements occuring in a column.
Deprecated. Use `datagrid-count' instead.
DATAGRID is the vector of structs. INDEX is the zero based column
number. If CODE is t, then decode data first. If nil, take code
as is. Returns an alist of (value . count) sorted by count descending."
  (declare (obsolete datagrid-count "1.0"))
  (datagrid--frequencies-alist datagrid index code))

(defun datagrid-column-quartiles (datagrid index &optional code)
  "Find the first, second, and third quartile of a column.
DATAGRID is the vector of structs. INDEX is the zero based column
number. If CODE is t, then decode data first. If nil, take code as is."
  (if-let* ((index (datagrid--resolve-col datagrid index))
	    (vec (if code
		     (datagrid-column-decode datagrid index)
		   (datagrid-column-data (aref datagrid index))))
	    (vec (seq-into (seq-filter #'identity vec) 'vector))
	    (vec (seq-sort #'< vec))
	    (len (length vec))
	    ((> len 0))
	    (1Q (aref vec (min (1- len) (/ (+ len 1) 4))))
	    (2Q (aref vec (min (1- len) (/ (+ len 1) 2))))
	    (3Q (aref vec (min (1- len) (/ (* 3 (+ len 1)) 4)))))
      `(("1Q" . ,1Q)
	("2Q" . ,2Q)
	("3Q" . ,3Q)
	("IQR" . ,(- 3Q 1Q)))))

(defun datagrid-column-mode (datagrid index &optional code)
  "Find the mode, most often occurring item, of a column.
DATAGRID is a datagrid struct. INDEX is the zero based column
number. CODE is nil if the data is not coded and non-nil if it
is. The output is a list of one or more mode values. This works
for strings or numbers."
  (let ((frequencies (datagrid--frequencies-alist datagrid index code)))
    (when frequencies
      (let ((high-freq (cdar frequencies)))
	(cl-loop for pair in frequencies
		 while (= high-freq (cdr pair))
		 collect (car pair))))))

(defun datagrid-column-unique (datagrid index &optional code)
  "Return unique items from a column as a vector.
Deprecated. Use `datagrid-distinct' for a datagrid-shaped result, or
`datagrid-pull' + `seq-uniq' for the bare vector.
DATAGRID is the vector of structs. INDEX is the zero based column
number. If CODE is t, then decode data first."
  (declare (obsolete datagrid-distinct "1.0"))
  (unless (datagridp datagrid)
    (error "Argument must be a datagrid"))
  (let* ((index (datagrid--resolve-col datagrid index))
	 (vec (if code (datagrid-column-decode datagrid index)
		(datagrid-column-data (aref datagrid index)))))
    (seq-uniq vec)))

(defun datagrid-column-mad (datagrid index &optional code)
  "Calculate the median absolute deviation.
DATAGRID is the vector of structs. INDEX is the zero based column
number. If CODE is t, then decode data first. If nil, take code
as is."
  (let* ((index (datagrid--resolve-col datagrid index))
	 (lst (delq nil (append (if code
				    (datagrid-column-decode datagrid index)
				  (datagrid-column-data (aref datagrid index)))
				nil)))
	 (lst-calc (seq-keep #'datagrid-prep-for-calc lst))
	 (median1 (datagrid-calc-function-wrapper "vmedian" lst-calc))
	 (lst-nums (mapcar (lambda (x) (if (stringp x)
					   (string-to-number x)
					 x))
			   lst))
	 (lst2 (mapcar (lambda (x) (abs (- x median1))) lst-nums)))
    (datagrid-calc-function-wrapper
     "vmedian" (seq-keep #'datagrid-prep-for-calc lst2))))

(defun datagrid-report-nominal (datagrid index)
  "Display column statistics for nominal data.
DATAGRID is a vector of datagrid structures. INDEX is the column to
analyze (zero-based integer or heading string)."
  (unless (datagridp datagrid)
    (error "Argument must be a datagrid"))
  (let* ((index (datagrid--resolve-col datagrid index))
	 (freq (seq-take (datagrid--frequencies-alist datagrid index nil) 5)))
    (append
     (list (datagrid-column-heading (elt datagrid index)))
     (list (cons "cardinality" (length freq)))
     (list (cons "mode" (datagrid-column-mode datagrid index)))
     (list (cons "frequency - five or fewer" freq)))))

(defun datagrid--report-numeric (datagrid index stats-name code convert include-mad)
  "Build a numeric summary report for DATAGRID column at INDEX.
STATS-NAME is a list of Calc function abbreviations to compute. CODE,
CONVERT have the same meaning as in the public report functions. If
INCLUDE-MAD is non-nil, append the mean absolute deviation."
  (unless (datagridp datagrid)
    (error "Argument must be a datagrid"))
  (let* ((index (datagrid--resolve-col datagrid index))
	 (vec (if code
		  (datagrid-column-decode datagrid index)
		(datagrid-column-data (aref datagrid index))))
	 (lst (if convert
		  (seq-keep #'datagrid-prep-for-calc vec)
		(seq-keep #'identity vec)))
	 (stats (cl-loop for statn in stats-name
			 collect (datagrid-calc-function-wrapper statn lst)))
	 (new-dg (vector (datagrid-column-make
			  :data (datagrid-unknown-type-to-number vec)))))
    (append
     (list (datagrid-column-heading (elt datagrid index)))
     (cl-mapcar #'cons stats-name stats)
     (list (cons "mode" (datagrid-column-mode new-dg 0)))
     (list (cons "quartiles" (datagrid-column-quartiles new-dg 0)))
     (when include-mad
       (list (cons "mean absolute deviation"
		   (datagrid-column-mad new-dg 0)))))))

(defun datagrid-report-ordinal (datagrid index &optional code convert)
  "Display column statistics for ordinal data.
DATAGRID is a vector of datagrid structures. INDEX is the column
to analyze. It uses zero based counting. If CODE is t then decode
the data before using the data. If CODE is nil take the data as
is. CONVERT tells the function to convert strings to numbers.

Mean and standard deviation are not included because this is
ordinal data."
  (datagrid--report-numeric
   datagrid index '("vcount" "vmin" "vmax" "vmedian") code convert t))

(defun datagrid-report-interval (datagrid index &optional code convert)
  "Display column statistics for interval data.
DATAGRID is a vector of datagrid structures. INDEX is the column
to analyze. It uses zero based counting. If CODE is t then decode
the data before using the data. If CODE is nil take the data as
is. CONVERT tells the function to convert strings to numbers."
  (datagrid--report-numeric
   datagrid index '("vcount" "vmin" "vmax" "vmedian" "vmean" "vsdev")
   code convert nil))

(defun datagrid-report-ratio (datagrid index &optional code convert)
  "Display column statistics for ratio data.
DATAGRID is a vector of datagrid structures. INDEX is the column
to analyze. It uses zero based counting. If CODE is t then decode
the data before using the data. If CODE is nil take the data as
is. CONVERT tells the function to convert strings to numbers.

RMS stands for root-mean-square or coefficient of variation."
  (datagrid--report-numeric
   datagrid index
   '("vcount" "vmin" "vmax" "vmedian" "vmean" "vgmean" "vsdev" "rms")
   code convert nil))

(defun datagrid-report-all-lom (datagrid)
  "Report on each column of data based on the level of measurement.
DATAGRID is a vector of datagrid structures.

This function will always decode a value if there is a code slot
provided for a datagrid-column struct. It will always convert strings to
Calc understandable numbers. This function will be slow for large data
sets.

This returns a cons structure. All columns with no specified level of
measurement are treated as nominal data."
  (cl-loop for x from 0 below (length datagrid)
	   collect (let ((code (if (datagrid-column-code (elt datagrid x))
				   t
				 nil))
			 (lom (datagrid-column-lom (elt datagrid x))))
		     (cons
		      (datagrid-column-heading (elt datagrid x))
		      (cond ((equal "ordinal" lom)
			     (datagrid-report-ordinal datagrid x code t))
			    ((equal "interval" lom)
			     (datagrid-report-interval datagrid x code t))
			    ((equal "ratio" lom)
			     (datagrid-report-ratio datagrid x code t))
			    (t
			     (datagrid-report-nominal datagrid x)))))))

(provide 'datagrid-stats)
;;; datagrid-stats.el ends here
