;;; datagrid-verbs.el --- Transformation verbs for datagrid -*- lexical-binding: t; -*-

;; Copyright (C) 2025 Joshua Lambert
;; Author: Joshua Lambert <jlambert@missouristate.edu>
;; Maintainer: Joshua Lambert <jlambert@missouristate.edu>
;; Keywords: tools, convenience
;; AI: This file contains code generated by LLMs.

;; This file is NOT part of GNU Emacs.

;; GNU Emacs is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;;; Commentary:

;; Datagrid transformation verbs that take a datagrid and return a
;; datagrid: head, mutate, rename, add-column, add-row, add-data,
;; set-headings, select, slice, remove-column, remove-row, sort,
;; rows-patch, coalesce, plus the mask-based filter helpers
;; (create-mask, filter-by-mask).

;; Verbs that are tightly coupled to reductions (summarize, group-by,
;; distinct) live in datagrid-stats.el instead.

;;; Code:
(require 'cl-lib)
(require 'seq)
(require 'datagrid)

(defun datagrid-head (datagrid &optional column-num row-num)
  "Return the first ROW-NUM rows and COLUMN-NUM columns of DATAGRID.
Indexing is logical. COLUMN-NUM (default 5) and ROW-NUM (default 5)
specify how many of each to take. The returned datagrid materializes
the slice and has nil row-order and col-order."
  (let* ((cols (datagrid-columns datagrid))
         (col-num (min (or column-num 5) (datagrid--ncols datagrid)))
         (row-num (min (or row-num 5) (datagrid--nrows datagrid))))
    (datagrid-make
     :columns
     (vconcat
      (cl-loop for j from 0 below col-num
               for src = (aref cols (datagrid--col-at datagrid j))
               for new = (datagrid-column-copy src)
               do (setf (datagrid-column-data new)
                        (seq-take (datagrid-pull datagrid j) row-num))
               collect new)))))

(defun datagrid-mutate (datagrid new-heading fn &rest source-cols)
  "Add or replace a column produced by applying FN row-wise.
DATAGRID is a datagrid. NEW-HEADING is the heading for the produced
column; if a column with that heading already exists it is replaced,
otherwise a new column is appended. FN receives one value per
SOURCE-COL, in order. SOURCE-COLS are logical column references
\(integer index or heading string)."
  (let* ((n-rows (datagrid--nrows datagrid))
         (col-vecs (mapcar
                    (lambda (c)
                      (datagrid-pull datagrid
                                     (datagrid--resolve-col datagrid c)))
                    source-cols))
	 (new-data (make-vector n-rows nil)))
    (dotimes (r n-rows)
      (aset new-data r
	    (apply fn (mapcar (lambda (v) (aref v r)) col-vecs))))
    (let* ((new-col (datagrid-column-make :heading new-heading :data new-data))
	   (existing (cl-position new-heading
				  (datagrid-get-headings datagrid)
				  :test #'equal)))
      (if existing
          (let* ((src-cols (datagrid-columns datagrid))
                 (ncols (datagrid--ncols datagrid))
                 (mat (cl-loop for j from 0 below ncols
                               for src = (aref src-cols
                                               (datagrid--col-at datagrid j))
                               for new = (datagrid-column-copy src)
                               do (setf (datagrid-column-data new)
                                        (datagrid-pull datagrid j))
                               collect new)))
            (setf (nth existing mat) new-col)
            (datagrid-make :columns (vconcat mat)))
        (datagrid-add-column datagrid new-col)))))

(defun datagrid-rename (datagrid col-or-renames &optional new-heading)
  "Return a new DATAGRID with one or more headings renamed.
If NEW-HEADING is non-nil, COL-OR-RENAMES is a single column index or
heading and that column's heading becomes NEW-HEADING. Otherwise
COL-OR-RENAMES is an alist ((OLD-OR-IDX . NEW) ...)."
  (let ((new-cols (copy-sequence (datagrid-columns datagrid))))
    (cl-flet ((rename-at (logical heading)
                (let* ((phys (datagrid--col-at datagrid logical))
                       (new-col (datagrid-column-copy (aref new-cols phys))))
                  (setf (datagrid-column-heading new-col) heading)
                  (setf (aref new-cols phys) new-col))))
      (if new-heading
          (rename-at (datagrid--resolve-col datagrid col-or-renames)
                     new-heading)
        (dolist (pair col-or-renames)
          (rename-at (datagrid--resolve-col datagrid (car pair))
                     (cdr pair)))))
    (datagrid-make :columns new-cols
                   :row-order (datagrid-row-order datagrid)
                   :col-order (datagrid-col-order datagrid))))

(defun datagrid-add-column (datagrid &rest datagrid-columns)
  "Add one or more datagrid-column structs to a datagrid.
DATAGRID is a datagrid. DATAGRID-COLUMNS is a list of datagrid-column
structs. The new columns are always expanded or truncated to fit the
length of the existing columns. All datagrid columns must have the same
length."
  (interactive)
  (when-let*
      ((datagridp (datagridp datagrid))
       (datagrid-cols-p (not (member nil (mapcar #'datagrid-column-p
						 datagrid-columns))))
       (ncols (datagrid--ncols datagrid))
       (col-len (datagrid--nrows datagrid))
       (materialized
        (vconcat
         (cl-loop for j from 0 below ncols
                  for src = (aref (datagrid-columns datagrid)
                                  (datagrid--col-at datagrid j))
                  for new = (datagrid-column-copy src)
                  do (setf (datagrid-column-data new)
                           (datagrid-pull datagrid j))
                  collect new)))
       (truncd (mapcar (lambda (dg-c) (datagrid-column-set-length dg-c col-len))
		       datagrid-columns)))
    (datagrid-make :columns (seq-concatenate 'vector materialized truncd))))

(defun datagrid-add-row (datagrid seq)
  "Add elements to the end of each datagrid-column.
DATAGRID a datagrid structure. SEQ is a list of sequences. Each of the
sequences in SEQ must be of equal length to the number of logical
datagrid-columns in datagrid."
  (interactive)
  (unless (datagridp datagrid)
    (error "DATAGRID is not a datagrid structure"))
  (unless (apply #'= (mapcar #'length seq))
    (error "The sequences in SEQ are not of equal length"))
  (let* ((src-cols (datagrid-columns datagrid))
         (ncols (datagrid--ncols datagrid)))
    (unless (= ncols (length (car seq)))
      (error (concat "The number of datagrid columns is not "
		     "equal to the length of sequences in SEQ.")))
    (let ((trans-seq (apply #'cl-mapcar #'list seq)))
      (datagrid-make
       :columns
       (vconcat
        (cl-loop for j from 0 below ncols
                 for src = (aref src-cols (datagrid--col-at datagrid j))
                 for added = (pop trans-seq)
                 for new = (datagrid-column-copy src)
                 do (setf (datagrid-column-data new)
                          (vconcat (datagrid-pull datagrid j) added))
                 collect new))))))

(defun datagrid--add-data-by-column (datagrid seqs)
  "Add data to DATAGRID columns.
SEQS is a sequence of sequences. Each sub-sequence is one logical
column's data. The sequences of data to add must be in the same order
as the logical datagrid-columns in DATAGRID. The length of SEQS must
equal the number of logical columns. If the sequences added are not of
equal length, then nil will be padded onto other columns to make the
data equal."
  (let* ((src-cols (datagrid-columns datagrid))
         (ncols (datagrid--ncols datagrid))
         (max-len (seq-max (seq-map #'length seqs))))
    (datagrid-make
     :columns
     (vconcat
      (cl-loop for j from 0 below ncols
               for src = (aref src-cols (datagrid--col-at datagrid j))
               for added-raw = (elt seqs j)
               for added = (seq-concatenate
                            'vector added-raw
                            (make-list (- max-len (length added-raw)) nil))
               for new = (datagrid-column-copy src)
               do (setf (datagrid-column-data new)
                        (vconcat (datagrid-pull datagrid j) added))
               collect new)))))

(defun datagrid-add-data (datagrid seqs &optional horizontal)
  "Add elements to each datagrid-column.
DATAGRID a datagrid structure. SEQS is a sequence of sequences. If
HORIZONTAL is nil, then each sub-sequence is one column's data. If non-nil,
then each sequence is one row's data. The default is nil. The sequences
are extended to keep datagrid-column-data lengths equal.

The sequences of data to add must be in the same order as the
datagrid-columns in DATAGRID."
  (interactive)
  (unless (datagridp datagrid)
    (error "DATAGRID is not a datagrid structure"))
  (if horizontal
      (datagrid--add-data-by-column datagrid (datagrid-safe-transpose seqs))
    (datagrid--add-data-by-column datagrid seqs)))

(defun datagrid-set-headings (datagrid heading-list)
  "Set all DATAGRID headings using HEADING-LIST.
HEADING-LIST is a list of strings where each string is a heading name.
The headings in the list must be in the same order as the
datagrid-columns in the datagrid."
  (let* ((src (datagrid-columns datagrid))
         (new-cols (copy-sequence src))
         (ncols (datagrid--ncols datagrid)))
    (cl-loop for x from 0 below ncols
             for phys = (datagrid--col-at datagrid x)
             for new-col = (datagrid-column-copy (aref new-cols phys))
	     do (setf (datagrid-column-heading new-col) (nth x heading-list))
             do (setf (aref new-cols phys) new-col))
    (datagrid-make :columns new-cols
                   :row-order (datagrid-row-order datagrid)
                   :col-order (datagrid-col-order datagrid))))

(defun datagrid-select (datagrid &rest cols)
  "Return a new datagrid projecting only COLS in the order given.
Each element of COLS is a zero-based logical column index or a heading
string. The result shares column data with DATAGRID and records a
col-order permutation. Composes with any existing col-order."
  (let* ((n (length cols))
         (new-order (make-vector n 0)))
    (cl-loop for i from 0
             for c in cols
             for logical = (datagrid--resolve-col datagrid c) do
             (aset new-order i (datagrid--col-at datagrid logical)))
    (datagrid-make :columns (datagrid-columns datagrid)
                   :row-order (datagrid-row-order datagrid)
                   :col-order new-order)))

(defun datagrid-slice (datagrid &rest row-indices)
  "Return a new datagrid containing only the rows at ROW-INDICES.
ROW-INDICES are zero-based row numbers."
  (datagrid--slice-rows datagrid row-indices))

(defun datagrid-remove-column (datagrid &rest cols)
  "Return DATAGRID without the columns in COLS.
Each element of COLS is a zero-based logical integer index or a
heading string."
  (when (datagridp datagrid)
    (let* ((src-cols (datagrid-columns datagrid))
           (ncols (datagrid--ncols datagrid))
           (drop (mapcar (lambda (c) (datagrid--resolve-col datagrid c)) cols))
           (kept (cl-loop for j from 0 below ncols
                          unless (memql j drop)
                          collect (aref src-cols
                                        (datagrid--col-at datagrid j)))))
      (datagrid-make :columns (vconcat kept)
                     :row-order (datagrid-row-order datagrid)))))

(defun datagrid-remove-row (datagrid index)
  "Return DATAGRID with the row at logical INDEX removed."
  (interactive)
  (let* ((src-cols (datagrid-columns datagrid))
         (ncols (datagrid--ncols datagrid)))
    (datagrid-make
     :columns
     (vconcat
      (cl-loop for j from 0 below ncols
               for src = (aref src-cols (datagrid--col-at datagrid j))
               for logical = (datagrid-pull datagrid j)
               for new-col = (datagrid-column-copy src)
               do (setf (datagrid-column-data new-col)
                        (vconcat (seq-take logical index)
                                 (seq-drop logical (1+ index))))
               collect new-col)))))

(defun datagrid-sort (datagrid col)
  "Return a new datagrid sorted by logical column COL.
COL is a zero-based column number or a heading string. Column data is
shared with DATAGRID; the result records a row-order permutation.
Composes with any existing row-order on DATAGRID."
  (let* ((vals (datagrid-pull datagrid col))
         (n (length vals))
         (indexed (cl-loop for i from 0 below n
                           collect (cons i (aref vals i))))
         (sorted (seq-sort-by #'cdr #'datagrid-unknown-type-sort indexed))
         (new-order (make-vector n 0)))
    (cl-loop for pair in sorted
             for k from 0 do
             (aset new-order k (datagrid--row-at datagrid (car pair))))
    (datagrid-make :columns (datagrid-columns datagrid)
                   :row-order new-order
                   :col-order (datagrid-col-order datagrid))))

(cl-defun datagrid-rows-patch (dg1 dg2 &key on cols)
  "Return a copy of DG1 with empty cells filled from matching rows of DG2.
This is the dplyr `rows_patch' operation: a keyed cross-table fill
that never overwrites existing non-empty values.

ON identifies the join key. It accepts an integer (same column
index in both grids), a string (heading present in both), or a
cons (X . Y) for per-grid index or heading. Keys are compared
with `equal'; empty keys (nil or empty string) never match. When
DG2 has duplicate keys, the first occurrence wins.

COLS is an alist ((FILL . SOURCE) ...). FILL is a column ref in
DG1 to fill and SOURCE is a column ref in DG2 to draw values
from. Each ref is an integer index or a heading string.

For each pair, every row of DG1 whose FILL value is nil or the
empty string is looked up by its key in DG2. When a match is
found and DG2's SOURCE value for that row is non-empty, the
value is copied into the returned datagrid. Existing non-empty
FILL values are left as is; DG1 is not modified.

Keys are compared `equal'-strictly: \"123\" and 123 are not
equal. Normalize types before calling if your key columns came
from different sources."
  (unless on (error ":on is required"))
  (unless cols (error ":cols is required"))
  (cl-labels ((empty-p (v) (or (null v) (and (stringp v) (string-empty-p v))))
	      (build-lookup (keys vals)
		(let ((ht (make-hash-table :test #'equal)))
		  (cl-loop for k across keys
			   for v across vals
			   unless (or (empty-p k) (empty-p v) (gethash k ht))
			   do (puthash k v ht))
		  ht)))
    (let* ((on-pair (pcase on
		      ((or (pred integerp) (pred stringp))
		       (cons (datagrid--resolve-col dg1 on)
			     (datagrid--resolve-col dg2 on)))
		      (`(,a . ,b)
		       (cons (datagrid--resolve-col dg1 a)
			     (datagrid--resolve-col dg2 b)))
		      (_ (error "Bad :on value: %S" on))))
	   (on1 (car on-pair))
	   (on2 (cdr on-pair))
           (src-cols1 (datagrid-columns dg1))
           (ncols1 (datagrid--ncols dg1))
           (result-cols
            (vconcat
             (cl-loop for j from 0 below ncols1
                      for src = (aref src-cols1 (datagrid--col-at dg1 j))
                      for new = (datagrid-column-copy src)
                      do (setf (datagrid-column-data new)
                               (datagrid-pull dg1 j))
                      collect new)))
	   (keys1 (datagrid-pull dg1 on1))
	   (keys2 (datagrid-pull dg2 on2)))
      (dolist (pair cols)
	(let* ((fill-idx (datagrid--resolve-col dg1 (car pair)))
	       (source-idx (datagrid--resolve-col dg2 (cdr pair)))
	       (lookup (build-lookup keys2 (datagrid-pull dg2 source-idx)))
	       (new-col (datagrid-column-copy (aref result-cols fill-idx)))
	       (new-data (copy-sequence (datagrid-column-data new-col))))
	  (cl-loop for i from 0 below (length new-data)
		   when (empty-p (aref new-data i))
		   do (when-let ((found (gethash (aref keys1 i) lookup)))
			(setf (aref new-data i) found)))
	  (setf (datagrid-column-data new-col) new-data)
	  (setf (aref result-cols fill-idx) new-col)))
      (datagrid-make :columns result-cols))))

(defun datagrid-coalesce (datagrid &rest col-groups)
  "Row-wise coalesce one or more groups of columns in DATAGRID.
Each group in COL-GROUPS is a list of column refs (integer index or
heading string). For each group, the first column's data is replaced
row-wise by the first non-empty value found across the group, where
\"empty\" means nil or the empty string. The non-first columns of
each group are dropped from the result. Other columns are unchanged.

Useful after `datagrid-full-join' to merge `email'/`email_2' style
sibling columns into one.

Example:

  (datagrid-coalesce joined
                     \\='(\"email\" \"email_2\")
                     \\='(\"phone\" \"phone_2\" \"phone_3\"))

Replaces `email' with the first non-empty of `email'/`email_2',
replaces `phone' with the first non-empty of
`phone'/`phone_2'/`phone_3', and drops `email_2', `phone_2', and
`phone_3'."
  (cl-labels ((empty-p (v) (or (null v) (and (stringp v) (string-empty-p v)))))
    (let* ((src-cols (datagrid-columns datagrid))
           (ncols (datagrid--ncols datagrid))
           (n-rows (datagrid--nrows datagrid))
           (mat (vconcat
                 (cl-loop for j from 0 below ncols
                          for src = (aref src-cols (datagrid--col-at datagrid j))
                          for new = (datagrid-column-copy src)
                          do (setf (datagrid-column-data new)
                                   (datagrid-pull datagrid j))
                          collect new)))
           (groups (mapcar (lambda (g)
			     (mapcar (lambda (c) (datagrid--resolve-col datagrid c))
				     g))
			   col-groups))
	   (drops (apply #'append (mapcar #'cdr groups))))
      (dolist (group groups)
	(let* ((target (car group))
	       (vecs (mapcar (lambda (i) (datagrid-column-data (aref mat i)))
			     group))
	       (out (make-vector n-rows nil))
               (new-col (datagrid-column-copy (aref mat target))))
	  (dotimes (r n-rows)
	    (aset out r (seq-some (lambda (v) (let ((x (aref v r)))
						(unless (empty-p x) x)))
				  vecs)))
	  (setf (datagrid-column-data new-col) out)
          (setf (aref mat target) new-col)))
      (datagrid-make
       :columns
       (vconcat (cl-loop for col across mat
			 for i from 0
			 unless (memq i drops)
			 collect col))))))

(defun datagrid-create-mask (datagrid pred col)
  "Create a mask for a DATAGRID column at COL.
PRED is a function of one argument. It will operate on the
datagrid column at COL. COL is a zero-based column number or a
string naming the column heading.

This simply returns a vector.

See the Info Manual for built-in predicates, equality functions,
and other useful functions to make predicate functions:

2.7 Type Predicates
2.8 Equality Predicates
3.3 Type Predicates for Numbers
3.4 Comparison of Numbers
4.2 Predicates for Strings
4.5 Comparison of Characters and Strings
5.2 Predicates on Lists
32.2 Predicates on Markers

Other common predicate function examples using lambdas:

 (lambda (x) (= x 15))
 (lambda (x) (eq x 15))
 (lambda (x) (equal x 15))
 (lambda (x) (string-equal x \"2025-03-31\"))
 (lambda (x) (string-prefix-p x \"2025\"))
 (lambda (x) (string-prefix-p x \"2025\"))
 (lambda (x) (> x \"2025\"))
 (lambda (x) (<= x \"2025\"))"
  (interactive)
  (let* ((cols (datagrid-columns datagrid))
         (vec (datagrid-pull datagrid col))
	 (mask (and (vectorp cols)
		    (> (length cols) 0)
		    (vectorp vec)
		    (cl-map 'vector pred vec))))
    mask))

(defun datagrid-filter-vector-by-mask (column-struct mask)
  "Filter a datagrid-column struct by a boolean MASK.
COLUMN-STRUCT is a datagrid-column structure. MASK must be a vector
with the same length as datagrid columns and the values must only be t
or nil. It is typically created by datagrid-create-mask-s. This is a
helper function for DATAGRID-FILTER-BY-MASK. It returns a
datagrid-column structure that copies the original but with the data
slot filtered."
  (let ((vec (datagrid-column-data column-struct))
	(new (datagrid-column-copy column-struct)))
    (setf (datagrid-column-data new)
	  (vconcat (cl-loop for m across mask
			    for v across vec
			    when m collect v)))
    new))

(defun datagrid-filter-by-mask (datagrid mask)
  "Use a boolean MASK to filter a DATAGRID.
MASK must be a sequence with the same length as datagrid columns
and the values must only be t or nil. The function returns a
DATAGRID. You can use DATAGRID-CREATE-MASK to create a mask.

The following code show an example workflow when using masks.

 (let* ((mygrid (datagrid-from-csv-buffer \"name-of-file.csv\" t))
        (index (datagrid-col-index-by-header mygrid \"heading-name\"))
        (func (lambda (x) (string-equal x \"filter-string\")))
        (mask (datagrid-create-mask mygrid func index)))
   (datagrid-filter-by-mask mygrid mask))"
  (let* ((mask-vec (vconcat mask))
         (kept (cl-loop for i from 0
                        for m across mask-vec
                        when m collect i)))
    (datagrid--slice-rows datagrid kept)))

(provide 'datagrid-verbs)
;;; datagrid-verbs.el ends here
