;;; datagrid.el --- Functions to manipulate a 2d data structure. -*- lexical-binding: t; -*-

;; Copyright (C) 2025 Joshua Lambert
;; Author: Joshua Lambert <jlambert@missouristate.edu>
;; Maintainer: Joshua Lambert <jlambert@missouristate.edu>
;; Created: 2025-03-31
;; Version: 0.1
;; Keywords: tools, convenience, sorting
;; URL: https://github.com/distichum/datagrid
;; Package-Requires: (seq calc cl-lib)
;; CSV functions require: (csv-mode)
;; AI: This file contains code generated by LLMs.

;; This file is NOT part of GNU Emacs.

;; GNU Emacs is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.
;;
;; GNU Emacs is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;; datagrid.el is a list of functions to handle table-like structures
;; in Emacs Lisp. A structure is made of one vector whose elements are
;; datagrid-column data structures. Each datagrid-column structure is
;; like a table column. A datagrid-column is defined by cl-defstruct.
;; Each datagrid-column has a data slot that contains a vector. All
;; dagatrid-columns in a datagrid must have an equal number of
;; elements in their datagrid-column-data slot. Think of it as tabular
;; data, a spreadsheet, a database table, or a dataframe. The purpose
;; of datagrid.el is to manipulate data in and do calculations on small to
;; medium sized data sets.

;; datagrid.el is not meant to display data in a buffer or manipulate
;; data that is already in a table. That said, the
;; datagrid-to-org-table function, executed in an Org Mode code block,
;; will produce a typical Org Mode table.

;; As of 2026-05-07, this package tries to align its grammar with
;; dplyr (https://dplyr.tidyverse.org/) while also honoring and
;; fitting into the Emacs Lisp ecosystem.

;;; Code:
;;;; Prerequisites
(require 'cl-lib)
(require 'seq)
(require 'calc)
(require 'calc-vec)

(declare-function csv-mode "csv-mode")
(declare-function csv-parse-current-row "csv-mode")
(declare-function make-vtable "vtable")


;;;; Variables:

(defvar datagrid-test-alist '(("date" . ("2025-03-31" "2025-04-01" "2025-04-02" "2025-04-03"))
			      ("location" . ("somewhere" "out" "there" "far"))
			      ("precipitation" . (0.5 0 .25 1))
			      ("high-temp" . (15 20 32 22))
			      ("rating" . ("Strongly disagree"
					   "Disagree"
					   "Neutral"
					   "Neutral")))
  "A test association list.")

(cl-defstruct (datagrid-column (:constructor datagrid-column-make)
                               (:copier datagrid-column-copy)
                               (:predicate datagrid-column--p))
  "A datagrid column contains a vector and attributes of that
vector. The vector may contain anything an Emacs vector may
contain, but some functions in datagrid.el expect a single
dimensional vector and consistent data types per vector.
The datagrid attributes are heading, data, lom, and code.

The Level Of Measurement (LOM) comes from Stanley Smith Stevens
and may be one of the following:

  nominal
  ordinal
  interval
  ratio
  nil (not from Stevens)

Values of nominal data types may be strings or numbers. Ordinal data in
datagrid.el may be strings or numbers. Interval data must be a number,
either an integer or a float. Ratio data must be a number, either an
integer or a float. Data types of nil may be of any data type. (Weighing
down the data structure with this slot may not be worth it. See if
anyone uses this or not. It can be helpful when automating summary data
presentation.)

CODE is an alist where the keys are one possible interpretation
of the research data and the value is another. For example:

 '(('Strongly disagree' . 1)
   ('Disagree'          . 2)
   ('Neutral'           . 3)
   ('Agree'             . 4)
   ('Strongly agree'    . 5))

Converting such categories to numerical codes better allows them to be
sorted and counted by computer programs."
  (heading nil :type string :documentation "Column heading")
  (data nil :type vector :documentation "The column's data")
  (lom nil :type string :documentation "Level of measurement.")
  (code nil :type list :documentation "An alist used to code or decode values."))

(cl-defstruct (datagrid (:constructor datagrid--make-raw)
                        (:copier datagrid-copy)
                        (:predicate datagrid--type-p))
  "A datagrid is a collection of datagrid-column structs with optional
row and column permutations.

COLUMNS is a vector of datagrid-column structs.

ROW-ORDER is a vector of integer indices into the column data,
defining a logical row ordering. A value of nil means rows are in
their natural physical order (0, 1, ..., N-1).

COL-ORDER is a vector of integer indices into COLUMNS, defining a
logical column ordering. A value of nil means columns are in their
natural physical order.

The order slots allow sort, filter, slice, and select operations to
return new datagrids that share underlying column data with the
source, by composing permutations instead of copying data."
  (columns nil :type vector :documentation "Vector of datagrid-column structs.")
  (row-order nil :type vector :documentation "Row permutation, or nil for identity.")
  (col-order nil :type vector :documentation "Column permutation, or nil for identity."))

(defsubst datagrid--row-at (dg i)
  "Physical row index for logical row I in DG.
Nil row-order means rows are in natural order."
  (let ((order (datagrid-row-order dg)))
    (if order (aref order i) i)))

(defsubst datagrid--col-at (dg j)
  "Physical column index for logical column J in DG.
Nil col-order means columns are in natural order."
  (let ((order (datagrid-col-order dg)))
    (if order (aref order j) j)))

(defsubst datagrid--nrows (dg)
  "Number of logical rows in DG.
Uses the length of `row-order' when set, otherwise the length of
the first column's data. Returns 0 when DG has no columns."
  (let ((order (datagrid-row-order dg))
        (cols (datagrid-columns dg)))
    (cond (order (length order))
          ((or (null cols) (zerop (length cols))) 0)
          (t (length (datagrid-column-data (aref cols 0)))))))

(defsubst datagrid--ncols (dg)
  "Number of logical columns in DG.
Uses the length of `col-order' when set, otherwise the length of
the `columns' vector."
  (let ((order (datagrid-col-order dg)))
    (if order (length order) (length (datagrid-columns dg)))))

(defun datagrid--columns-equal-length-p (columns)
  "Non-nil when COLUMNS is empty or every datagrid-column shares one data length."
  (or (null columns)
      (zerop (length columns))
      (let ((first-len (length (datagrid-column-data (aref columns 0)))))
        (cl-every (lambda (c)
                    (and (datagrid-column--p c)
                         (= (length (datagrid-column-data c)) first-len)))
                  columns))))

(cl-defun datagrid-make (&key columns row-order col-order)
  "Construct a datagrid.
COLUMNS is a vector of datagrid-column structs that must all have the
same data length. ROW-ORDER and COL-ORDER are optional permutation
vectors, or nil for natural order."
  (unless (datagrid--columns-equal-length-p columns)
    (error "datagrid-make: COLUMNS have unequal data lengths"))
  (datagrid--make-raw :columns columns
                      :row-order row-order
                      :col-order col-order))

(defun datagridp (x)
  "Return non-nil if X is a datagrid with equal-length columns."
  (and (datagrid--type-p x)
       (datagrid--columns-equal-length-p (datagrid-columns x))))

(defvar datagrid-column-example
  (datagrid-column-make :heading "I like Emacs."
			:data [5 5 5 5 5]
			:lom "ordinal"
			:code  '(("Strongly disagree" . 1)
				 ("Disagree"          . 2)
				 ("Neutral"           . 3)
				 ("Agree"             . 4)
				 ("Strongly agree"    . 5)))
  "An example datagrid-column structure.")

(defvar datagrid-example
  (datagrid-make
   :columns
   (vector (datagrid-column-make
	    :heading "date"
	    :data ["2025-03-31" "2025-04-01" "2025-04-02" "2025-04-03"]
	    :lom nil)
	   (datagrid-column-make
	    :heading "location"
	    :data ["somewhere" "out" "there" "far"]
	    :lom "ordinal"
	    :code  '(("somewhere" . 1)
		     ("out"       . 2)
		     ("there"     . 3)
		     ("far"       . 4)))
	   (datagrid-column-make
	    :heading "precipitation"
	    :data [0.5 0 .25 1]
	    :lom "ratio")
	   (datagrid-column-make
	    :heading "high-temp"
	    :data [15 20 32 22]
	    :lom "interval")
	   (datagrid-column-make
	    :heading "rating"
	    :data ["good" "bad" "ugly" "uglier"]
	    :lom "nominal")))
  "An example datagrid for testing.
The columns slot is a vector of datagrid-column structs.")


;;;; Helper functions:
(defun datagrid-safe-transpose (seq-of-seqs)
  "Transpose a sequence of sequences and pad short rows if needed.
SEQ-OF-SEQS is a sequence of sequences. The result is a list of lists."
  (let* ((max-cols (apply #'max (mapcar #'length seq-of-seqs)))
	 (listed (seq-map (lambda (seq) (if (listp seq)
					    seq
					  (append seq nil)))
			  seq-of-seqs))
	 (padded (cl-loop for row in listed
			  collect (append row
					  (make-list (- max-cols (length row))
						     nil)))))
    (apply #'cl-mapcar #'list padded)))

(defun datagrid-unknown-type-to-number (seq)
  "Convert a sequence of unknown types to numbers.
Convert a SEQ of unknown data types to a sequence of
numbers. Leave nil values in place."
  (let ((seqnow (seq-into seq 'list)))
    (vconcat
     (cl-loop for item in seqnow
	      collect (cond ((stringp item) (if (equal item "")
						nil
					      (string-to-number item)))
			    ((numberp item) item)
			    ((null item) item)
			    (t (error "%s cannot be coerced into a number"
				      item)))))))

(defun datagrid-unknown-type-sort (a b)
  "Predicate sort function when type is unknown.
A and B must be the same type but the type may not be known ahead of
time.

Generated by Claude AI and adapted: 2025-06-13."
  (cond
   ((numberp a) (< a b))
   ((stringp a) (string< a b))
   ((symbolp a) (string< (symbol-name a) (symbol-name b)))
   ;; Use string comparison if others don't match.
   (t (string< (format "%s" a) (format "%s" b)))))


;;;; datagrid-column functions
(defun datagrid-column-p (dg-c)
  "Return non-nil if DG-C is a datagrid-column, nil otherwise.
HEADINGS must be strings. DATA must be a vector. LOM must be a string.
CODE must be an alist."
  (and (datagrid-column--p dg-c)
       (or (null (datagrid-column-heading dg-c))
           (stringp (datagrid-column-heading dg-c)))
       (or (null (datagrid-column-data dg-c))
           (vectorp (datagrid-column-data dg-c)))
       (or (null (datagrid-column-lom dg-c))
           (stringp (datagrid-column-lom dg-c)))
       (or (null (datagrid-column-code dg-c))
           (listp (datagrid-column-code dg-c)))))

(defun datagrid-column-set-length (dg-c N)
  "Truncate or expand the data in a datagrid column.
Data may be truncated, extended with nils, or left the same. DG-C is the
datagrid column. N is the length.

This creates a new vector and replaces the old."
  (when-let* ((datagrid-column-p dg-c)
	      (vec (datagrid-column-data dg-c))
	      (len (length (datagrid-column-data dg-c))))
    (if (= len N)
	dg-c
      (let ((new (datagrid-column-copy dg-c)))
	(setf (datagrid-column-data new)
	      (if (< N len)
		  (seq-take vec N)
		(seq-concatenate 'vector vec (make-vector (- N len) nil))))
	new))))

(defun datagrid--column-add-data (dg-c seq)
  "Add one or more elements to a datagrid column's data.
DG-C is the datagrid column. SEQ is a sequence. The result of this
function is a datagrid-column.

WARNING. Use only in conjunction with DATAGRID-ADD-ROW which keeps the
datagrid column lengths in sync."
  (when-let* ((datagrid-column-p dg-c)
	      (data (datagrid-column-data dg-c))
	      (new (datagrid-column-copy dg-c)))
    (setf (datagrid-column-data new) (vconcat data seq))
    new))


;;;; Create datagrid-column methods for seq
(cl-defmethod seq-elt ((datagrid-column datagrid-column) n)
  "Return the Nth element of the DATAGRID-COLUMN data."
  (elt (datagrid-column-data datagrid-column) n))

;; These methods ignore datagrid-column slots other than the :data
;; slot. streams.el and ordered-set.el are good examples.

(cl-defmethod seq-length ((datagrid-column datagrid-column))
  "Return the length of the DATAGRID-COLUMN data."
  (length (datagrid-column-data datagrid-column)))

(cl-defmethod seq-do (function (datagrid-column datagrid-column))
  "Apply FUNCTION to each element of DATAGRID-COLUMN data.
Return the original DATAGRID-COLUMN. Presumably, FUNCTION has
useful side effects."
  (mapc function (datagrid-column-data datagrid-column))
  datagrid-column)

(cl-defmethod seqp ((_datagrid-column datagrid-column))
  "DATAGRID-COLUMN is a sequence or sequences."
  t)

(cl-defmethod seq-subseq ((datagrid-column datagrid-column) start &optional end)
  "Return a new DATAGRID-COLUMN containing a range of elements.
START is the first element to select and END is the last. END is
exclusive."
  (let ((new (datagrid-column-copy datagrid-column)))
    (setf (datagrid-column-data new)
	  (seq-take (seq-drop (datagrid-column-data datagrid-column) start)
		    (- end start)))
    new))

(cl-defmethod seq-into-sequence ((datagrid-column datagrid-column))
  "Return DATAGRID-COLUMN as a sequence."
  ;; Since a datagrid-column is a record data type, this does nothing
  ;; but expose the sequence part of datagrid-column.
  (datagrid-column-data datagrid-column))

(cl-defmethod seq-copy ((datagrid-column datagrid-column))
  "Return a shallow copy of DATAGRID-COLUMN."
  (datagrid-column-copy datagrid-column))

(cl-defmethod seq-into ((datagrid-column datagrid-column) type)
  "Convert DATAGRID-COLUMN into a sequence of type TYPE.
This is lossy because other DATAGRID-COLUMN slots are not copied."
  (seq-into (seq-into-sequence datagrid-column) type))

(cl-defmethod seq-into (sequence (_type (eql datagrid-column)))
  "Convert SEQUENCE into a DATAGRID-COLUMN."
  (datagrid-column-make :data (seq-into sequence 'vector)))



;;;; Making and changing data grids
(defun datagrid-from-alist (alist &optional headings extend-uneven)
  "Create a datagrid from an ALIST using the datagrid-column struct.
If HEADINGS is nil, the alist has no headings. If HEADINGS is non-nil,
then it does. If EXTEND-UNEVEN is non-nil, then extend lists with nil so
that they are all the same length. If EXTEND-UNEVEN is nil, then take
only the data for a row up to the minimum row length."
  (interactive)
  (let* ((ralist (reverse alist))
         (values (mapcar (if headings #'cdr #'identity) ralist))
         (min-length (apply (if extend-uneven #'max #'min)
                            (mapcar #'length values)))
	 result)
    (dolist (item ralist)
      (let* ((label (if headings (car item) nil))
             (data (if headings (cdr item) item))
             (extended (if extend-uneven
                           (append data (make-list (max 0 (- min-length (length data))) nil))
			 (seq-take data min-length))))
	(push (datagrid-column-make
               :heading label
               :data (vconcat extended))
              result)))
    (datagrid-make :columns (vconcat result))))

(defun datagrid-make-empty (col-num row-num &optional init heading-list)
  "Create a new datagrid with specified dimensions.
COL-NUM is the number of columns. ROW-NUM is the number of rows in
each column. HEADING-LIST is a list whose length must equal the
number of columns. INIT is the value of each element in each :data
slot vector in each datagrid-column struct."
  (let ((headings (or heading-list (make-list col-num nil))))
    (datagrid-make
     :columns
     (cl-loop for elt from 1 to col-num
              for init-vec = (make-vector row-num init)
              for dg-col = (datagrid-column-make :data init-vec)
              do (setf (datagrid-column-heading dg-col) (elt headings (1- elt)))
              collect dg-col into parent
              finally return (vconcat parent)))))


(defun datagrid-from-vectors (&rest vectors)
  "Create a datagrid from VECTORS.
The first element in each vector is the heading."
  (interactive)
  (unless (and vectors (cl-every #'vectorp vectors))
    (error "All arguments must be vectors"))
  (datagrid-make
   :columns
   (vconcat (cl-loop for v in vectors
		     collect (datagrid-column-make
			      :heading (elt v 0)
			      :data (seq-drop v 1))))))

(defun datagrid-from-csv-buffer (buffer-or-name &optional headings)
  "Return a datagrid from an open csv buffer.
BUFFER-OR-NAME is the buffer name. If HEADINGS is nil, then there
is not a headings row. If t, then there is. The default is nil.

REQUIRES: CSV-MODE"
  (require 'csv-mode)
  (save-current-buffer
    (set-buffer buffer-or-name)
    (save-excursion
      (let ((data nil)
	    (2d-by-column nil))
	(goto-char (point-min))
	(while (not (eobp))
	  (setq data (cons (csv-parse-current-row) data))
	  (forward-line))
	;; Transpose the list of lists to make it a column store.
	(setq 2d-by-column (datagrid-safe-transpose (nreverse data)))
	(datagrid-make
	 :columns
	 (vconcat (cl-loop for item in 2d-by-column
                           collect (datagrid-column-make
				    :heading (when headings (elt item 0))
				    :data (vconcat (if headings
						       (seq-drop item 1)
						     item))))))))))

(defun datagrid-from-csv-file (file-path &optional headings)
  "Return a datagrid from a CSV file at FILE-PATH.
If HEADINGS is nil, then there is not a headings row. If t, then
there is. The default is nil.

REQUIRES: CSV-MODE

PCSV is a package in MELPA that can correctly parse multiline CSV
fields. Use it with datagrid.el as follows:

  (datagrid-from-alist
   (datagrid-safe-transpose (pcsv-parse-file FILE))
   HEADINGS
   EXTEND-UNEVEN)"
  (require 'csv-mode)
  (with-temp-buffer
    (insert-file-contents file-path)
    (goto-char (point-min))
    (while (search-forward "\r" nil t)
      (replace-match "" nil t))
    (csv-mode)
    (datagrid-from-csv-buffer (current-buffer) headings)))

(defun datagrid--csv-quote-field (field)
  "Return FIELD as a CSV-safe string.
Quote and escape if FIELD contains a comma, double quote, or newline.
Nil becomes an empty field."
  (cond
   ((null field) "")
   (t (let ((s (if (stringp field) field (format "%s" field))))
        (if (string-match-p "[\",\n\r]" s)
            (concat "\"" (replace-regexp-in-string "\"" "\"\"" s) "\"")
          s)))))

(defun datagrid--insert-csv (datagrid &optional headings)
  "Insert DATAGRID at point in the current buffer as CSV.
If HEADINGS is non-nil, insert a heading row first. Iterates DATAGRID
in logical row and column order. This is lossy: the LOM and CODE slots
are not preserved."
  (unless (datagridp datagrid)
    (error "Argument must be a datagrid"))
  (let* ((cols (datagrid-columns datagrid))
         (ncols (datagrid--ncols datagrid))
         (nrows (datagrid--nrows datagrid)))
    (when headings
      (insert (mapconcat #'datagrid--csv-quote-field
                         (append (datagrid-get-headings datagrid) nil)
                         ","))
      (insert "\n"))
    (cl-loop for i from 0 below nrows
             for phys-row = (datagrid--row-at datagrid i) do
             (insert (mapconcat
                      (lambda (j)
                        (let* ((phys-col (datagrid--col-at datagrid j))
                               (col (aref cols phys-col)))
                          (datagrid--csv-quote-field
                           (aref (datagrid-column-data col) phys-row))))
                      (number-sequence 0 (1- ncols))
                      ","))
             (insert "\n"))))

(defun datagrid-write-csv (datagrid file-path &optional headings)
  "Write DATAGRID to FILE-PATH as CSV.
If HEADINGS is non-nil, write a heading row first. This is lossy:
the LOM and CODE slots are not preserved."
  (with-temp-file file-path
    (datagrid--insert-csv datagrid headings)))

(defun datagrid-to-csvbuf (datagrid buffer-name &optional headings)
  "Insert DATAGRID as CSV into a new buffer named BUFFER-NAME and switch to it.
A fresh buffer is generated (the name is uniquified if needed). If
HEADINGS is non-nil, insert a heading row first. Returns the new
buffer. This is lossy: the LOM and CODE slots are not preserved."
  (let ((buf (generate-new-buffer buffer-name)))
    (with-current-buffer buf
      (datagrid--insert-csv datagrid headings)
      (goto-char (point-min)))
    (switch-to-buffer buf)
    buf))

(defun datagrid-to-vec-of-vec (datagrid)
  "Create a vector of vectors from DATAGRID in logical order.
This is a lossy function because it does not maintain the headings,
code, or lom slot."
  (let ((ncols (datagrid--ncols datagrid)))
    (vconcat (cl-loop for j from 0 below ncols
                      collect (datagrid-pull datagrid j)))))

(defun datagrid-to-alist (datagrid &optional headings)
  "Create an alist from a DATAGRID.
If HEADINGS is non-nil, return headings as the first item in each
list. Otherwise return only data."
  (let ((hdngs (and headings
		    (append (datagrid-get-headings datagrid) nil)))
	(data (datagrid-to-vec-of-vec datagrid)))
    (cl-loop for x from 0 below (length data)
	     collect (if hdngs
			 (append (list (elt hdngs x))
				 (append (elt data x) nil))
		       (append (elt data x) nil)))))

(defun datagrid-to-vtable (datagrid buffer-name &optional headings)
  "Create a vtable from a DATAGRID.
If HEADINGS is non-nil, create a vtable with a headings row."
  (let ((hdngs (and headings
		    (append (datagrid-get-headings datagrid) nil)))
	(data (datagrid-safe-transpose (datagrid-to-alist datagrid))))
    (get-buffer-create buffer-name)
    (with-current-buffer buffer-name
      (erase-buffer)
      (make-vtable
       :columns hdngs
       :objects data)
      (goto-char (point-min))
      (pop-to-buffer buffer-name))))

(defun datagrid-to-org-table (datagrid)
  "Manipulate DATAGRID to create an Org table."
  (datagrid-safe-transpose (datagrid-to-alist datagrid t)))

(defun datagrid-column-add-code (datagrid index code)
  "Add coding data to a datagrid-column.
DATAGRID is a datagrid struct. INDEX is a number or a list of
numbers. The function adds CODE in the CODE slot of DATAGRID. If INDEX
is a list, then CODE is applied to all datagrid columns at those
positions.

CODE is an alist where the keys are one possible interpretation
of the research data and the value is another. For example:

 ((\"Strongly disagree\" . 1)
  (\"Disagree\"          . 2)
  (\"Neutral\"           . 3)
  (\"Agree\"             . 4)
  (\"Strongly agree\"    . 5))"
  (let* ((src (datagrid-columns datagrid))
         (new-cols (copy-sequence src))
         (targets (if (listp index) index (list index))))
    (dolist (i targets)
      (let* ((phys (datagrid--col-at datagrid i))
             (new-col (datagrid-column-copy (aref new-cols phys))))
        (setf (datagrid-column-code new-col) code)
        (setf (aref new-cols phys) new-col)))
    (datagrid-make :columns new-cols
                   :row-order (datagrid-row-order datagrid)
                   :col-order (datagrid-col-order datagrid))))


;;;; Datagrid utilities; results are not datagrids
(defun datagrid-dimensions (datagrid)
  "Return the logical dimensions of DATAGRID as (columns . rows)."
  (interactive)
  (cons (datagrid--ncols datagrid) (datagrid--nrows datagrid)))

(defun datagrid-get-elt (datagrid column-num row-num)
  "Get a value at a specific column and row.
COLUMN-NUM and ROW-NUM are zero-based logical indices."
  (interactive)
  (let* ((cols (datagrid-columns datagrid))
         (dg-col (aref cols (datagrid--col-at datagrid column-num))))
    (aref (datagrid-column-data dg-col)
          (datagrid--row-at datagrid row-num))))

(defun datagrid--resolve-col (datagrid spec)
  "Resolve a logical column index in DATAGRID from SPEC.
SPEC is an integer index or a heading string."
  (cond ((integerp spec) spec)
	((stringp spec)
	 (or (cl-position spec (datagrid-get-headings datagrid) :test #'equal)
	     (error "No column with heading %S in datagrid" spec)))
	(t (error "Bad column spec: %S" spec))))

(defun datagrid-pull (datagrid col)
  "Return the data vector of logical column COL in DATAGRID.
COL is a zero-based logical index or a heading string. If DATAGRID
has a row-order, returns a freshly built vector in logical order;
otherwise returns the underlying data vector (shared)."
  (let* ((cols (datagrid-columns datagrid))
         (j (datagrid--col-at datagrid (datagrid--resolve-col datagrid col)))
         (data (datagrid-column-data (aref cols j)))
         (order (datagrid-row-order datagrid)))
    (if order
        (vconcat (cl-loop for i across order collect (aref data i)))
      data)))

(defun datagrid-get-col-data (datagrid index)
  "Extract a column vector from DATAGRID at logical INDEX.
Deprecated. Use `datagrid-pull' instead."
  (declare (obsolete datagrid-pull "1.0"))
  (datagrid-pull datagrid index))

(defun datagrid-get-row-data (datagrid row-num)
  "Extract logical row ROW-NUM from DATAGRID as a fresh vector."
  (let* ((cols (datagrid-columns datagrid))
         (ncols (datagrid--ncols datagrid))
         (phys-row (datagrid--row-at datagrid row-num)))
    (vconcat (cl-loop for j from 0 below ncols
                      for phys-col = (datagrid--col-at datagrid j)
                      collect (aref (datagrid-column-data (aref cols phys-col))
                                    phys-row)))))

(defun datagrid-get-headings (datagrid)
  "Create a vector of all DATAGRID headings in logical column order."
  (let ((cols (datagrid-columns datagrid))
        (ncols (datagrid--ncols datagrid)))
    (vconcat (cl-loop for j from 0 below ncols
                      collect (datagrid-column-heading
                               (aref cols (datagrid--col-at datagrid j)))))))

(defun datagrid-col-index-by-header (datagrid header-text)
  "Return the logical column index in DATAGRID with HEADER-TEXT.
Return nil if the header is not found."
  (let ((cols (datagrid-columns datagrid))
        (ncols (datagrid--ncols datagrid)))
    (cl-loop for j from 0 below ncols
             for phys = (datagrid--col-at datagrid j)
             when (equal (datagrid-column-heading (aref cols phys))
                         header-text)
             return j)))

(defun datagrid-col-data-by-header (datagrid header-text)
  "Extract column data from DATAGRID by HEADER-TEXT.
Deprecated. Use `datagrid-pull' instead."
  (declare (obsolete datagrid-pull "1.0"))
  (datagrid-pull datagrid header-text))

(defun datagrid-column-decode (datagrid index)
  "Output a decoded datagrid column as a vector.
DATAGRID is the vector of structs. INDEX is the column number to
code (zero based) or a heading string. The datagrid-column must have
DATAGRID-COLUMN-CODE to decode the data. If not, then the output
is simply DATAGRID-COLUMN-DATA.

 A Lickert scale DATAGRID-COLUMN-CODE may be coded as follows.

\\='((\"Strongly Disagree\" 1)
     (\"Disagree\"	2)
     (\"Neither Agree nor Disagree\" 3)
     (\"Agree\" 4)
     (\"Strongly Agree\" 5))

The DATAGRID-COLUMN-DATA may look like the following.

 [\"Strongly Disagree\" \"Agree\" \"Disagree\"]

This function will output the following.

 [1 4 2]

TODO: Provide better feedback regarding data values which are not
found in the coding alist. I'm not sure what kind of feedback at
this point. I should probably create a function that returns the
original data values that return nil."
  (unless (datagridp datagrid)
    (error "Argument must be a datagrid"))
  (let* ((cols (datagrid-columns datagrid))
         (phys-col (datagrid--col-at datagrid index))
         (col (aref cols phys-col))
         (vec (datagrid-pull datagrid index))
	 (code (datagrid-column-code col))
	 (coded-alist (when (and code
				 (listp code)
				 (cl-every #'consp code))
			(seq-map (lambda (x)
				   (cdr (assoc x code #'string-equal)))
				 vec))))
    (if coded-alist (vconcat coded-alist) vec)))



;;;; Slicing primitives (used by verbs and stats)
(defun datagrid--slice-rows (datagrid rows)
  "Return a datagrid restricted to logical ROWS of DATAGRID.
ROWS is a list of zero-based logical row indices. Column data is
shared with DATAGRID; only the row-order is set. Composes with any
existing row-order."
  (let* ((n (length rows))
         (new-order (make-vector n 0)))
    (cl-loop for i from 0
             for r in rows do
             (aset new-order i (datagrid--row-at datagrid r)))
    (datagrid-make :columns (datagrid-columns datagrid)
                   :row-order new-order
                   :col-order (datagrid-col-order datagrid))))

(defun datagrid--select-rows (datagrid rows)
  "Return a vector of vectors from DATAGRID containing only ROWS.
ROWS is a list of physical row indices. The result is a vector of
vectors of column data (not a datagrid)."
  (let ((n (length rows))
        (cols (datagrid-columns datagrid)))
    (vconcat
     (cl-loop for col across cols
	      collect (let* ((data (datagrid-column-data col))
			     (result (make-vector n nil)))
			(cl-loop for i from 0
				 for row in rows
				 do (aset result i (aref data row)))
			result)))))


;;; Provide
(provide 'datagrid)

(require 'datagrid-verbs)
(require 'datagrid-stats)
(require 'datagrid-join)
;;; datagrid.el ends here
